version: "3.7"
services:
  db:
    image: postgres:alpine
    container_name: p_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: schooldb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - ./V1__init_schema.sql:/docker-entrypoint-initdb.d/V1__init_schema.sql
