version: "3.3"

services:
  postgres:
    image: postgres:13.3
    container_name: p_container
    environment:
      - POSTGRES_USER: "user"
      - POSTGRES_PASSWORD: "pass"
      - POSTGRES_DB: "social_db"
    ports:
      - "5432:5432"
